include: [".well-known"]

description: "My personal website and projects"

collections:
  notes:
    output: true
    permalink: /:collection/:categories/:name:output_ext

host: 0.0.0.0
name: "Bruno Del Monde"
